repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml

# - repo: https://github.com/keivanzavari/pre-commit-hook
#   rev: ''
#   hooks:
#     - id: yapf
