repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml

- repo: local
  hooks:
  - id: yapf
    name: yapf
    description: This hook ...
    entry: yapf
    language: python
    files: \.(py)$
    args: [-i]
